try {
  throw new Error("Error!");
} catch {
  console.log("An error occurred!");
}
